# Generated by Django 5.0.3 on 2024-03-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_venue_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('musicians', models.ManyToManyField(to='bands.musician')),
            ],
        ),
    ]
